name 'puppet-basenode'
version '0.0.1'
source 'https://github.com/openstack-hyper-v/puppet-basenode.git'
author 'Nick Meier <Nick.Meier@microsoft.com'
license 'Apache 2.0'
summary 'Module for configuring standard node options'
description 'puppet module for configuring  basic node properties'
dependency 'puppetlabs/ntp'
dependency 'stephenjohnson/puppet'
dependency 'puppetlabs/mount_providers'
dependency 'rtyler/jenkins'
